/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package newpackage;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ForthPage extends javax.swing.JFrame {

    /**
     * Creates new form ForthPage
     */
    public ForthPage() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(447, 661));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(222, 201, 162));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 570, 100, 25);

        jButton2.setBackground(new java.awt.Color(222, 201, 162));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText(" End >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 570, 100, 25);

        jButton3.setBackground(new java.awt.Color(222, 201, 162));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 570, 80, 25);

        jButton4.setBackground(new java.awt.Color(222, 201, 162));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(120, 240, 90, 23);

        jButton5.setBackground(new java.awt.Color(222, 201, 162));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(119, 400, 90, 23);

        jTextPane1.setBackground(new java.awt.Color(242, 228, 200));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 150, 70);

        jTextPane2.setBackground(new java.awt.Color(242, 228, 200));
        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 280, 150, 22);

        jTextPane3.setBackground(new java.awt.Color(242, 228, 200));
        jScrollPane3.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(60, 340, 150, 60);

        jTextField1.setBackground(new java.awt.Color(242, 228, 200));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 440, 150, 70);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel6.setText("Result");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 420, 150, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel5.setText("Enter code to decrypt");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 320, 150, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel4.setText("Enter key");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 260, 150, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel3.setText("Enter text to encrypt");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 150, 150, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Polyalphabetic Substitution");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(81, 70, 290, 28);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/copiale-cipher-decoder-ring-1024x791.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 160, 200, 260);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/old-key-on-a-scroll-with-letters.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 420, 200, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/papirus_dyplom542.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 429, 618);

        setSize(new java.awt.Dimension(445, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     //БУТОН ЗА ПРЕДИШНА СТРАНИЦА(ВИЖЕНЕР)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ThirdPage tp=new ThirdPage();
       tp.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //БУТОН ЗА СЛЕДВАЩА СТРАНИЦА
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ending en=new Ending();
        en.setVisible(true);
        dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
 //БУТОН ЗА СТРАНИЦА - МЕНЮ
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Menu mn =new Menu();
mn.setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


//БУТОН ЗА КРИПТИРАНЕ
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      String str=jTextPane1.getText().replace(' ', '_');
      str=str.toUpperCase();
      String key=jTextPane2.getText();
      key=key.toUpperCase();
      
      while(str.length()<key.length()){
         str+="_";
      }
      
      if(str.length()>=key.length()){
      int n=key.length();
      for(int i=0;key.length()!=str.length();i++){
          if(i==n){
              i=0;
          }
          key=key+key.charAt(i);
      }
      
      
      
      }
     // String M ="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЬЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 \"-*";
      String M1 ="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЬЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_\"-*";
      Boolean bl=false,isOk=false;
      if(str.length()<=300){
         for(int i=0;i<str.length();i++){
             for(int j=0;j<M1.length();j++){
                 if(str.charAt(i)==M1.charAt(j)){
                     bl=true;
                 }
             }
             if(bl==false){
                 String message = "The text entered should should contain only"
                         + " symbols from the array:\n M={АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЬЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 \"-*}; ";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
            isOk=true;
             break;
             }
             else bl=false;
         }
         if(isOk==false)
         jTextField1.setText(Encrypt(str,M1,key));
          
      }
      else{
          String message = "The text entered should shouldn't be longer than 300 symbols";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    
    //БУТОН ЗА ДЕКРИПТИРАНЕ
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      String str=jTextPane3.getText().replace(' ', '_');
      str=str.toUpperCase();
      String key=jTextPane2.getText();
      key=key.toUpperCase();
      
      if(str.length()>=key.length()){
      int n=key.length();
      for(int i=0;key.length()!=str.length();i++){
          if(i==n){
              i=0;
          }
          key=key+key.charAt(i);
      }
      System.out.println(key);
      }
      String M ="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЬЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_\"-*";
      Boolean bl=false,isOk=false;
      if(str.length()<=300){
         for(int i=0;i<str.length();i++){
             for(int j=0;j<M.length();j++){
                 if(str.charAt(i)==M.charAt(j)){
                     bl=true;
                 }
             }
             if(bl==false){
                 String message = "The text entered should should contain only"
                         + " symbols from the array:\n M={АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЬЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_\"-*}; ";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
            isOk=true;
             break;
             }
             else bl=false;
         }
         if(isOk==false)
         jTextField1.setText(Decrypt(str,key,M));
          
      }
      else{
          String message = "The text entered should shouldn't be longer than 300 symbols";
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
      }
        

    }//GEN-LAST:event_jButton5ActionPerformed

    public String Decrypt(String str,String key,String arr1){
        int counter1=0;
        int counter2=0;
        
        StringBuilder sb=new StringBuilder();
        for(int i=0;i<key.length();i++){
        for(int j=0;j<arr1.length();j++){
            if(arr1.charAt(j)==key.charAt(i)) {
                counter1=j;
                
            }
            if(arr1.charAt(j)==str.charAt(i)){
                counter2=j;
                
            }
            }
        if(counter1>counter2){
            int n=counter1-counter2;
         sb.append(arr1.charAt(arr1.length()-n-1));
      
        }
        else if(counter1<counter2){
            
         sb.append(arr1.charAt(counter2-counter1-1));
         
        }
        else {
            sb.append(arr1.charAt(arr1.length()-1));
           
             
        }
        
        }
            
        return sb.toString().replace('_', ' ');
    }
    public String Encrypt(String str,String arr,String key){
        int counter1=0;
        int counter2=0;
        StringBuilder sb=new StringBuilder();
        for(int i=0;i<key.length();i++){
        for(int j=0;j<arr.length();j++){
            if(arr.charAt(j)==key.charAt(i)) {
                counter1=j;
                
            }
            if(arr.charAt(j)==str.charAt(i)){
                counter2=j;
                
            }
            }
        int n=counter1+counter2+1;
        if(n<arr.length()){
            
        sb.append(arr.charAt(n));    
        }
        else {
            while(n>arr.length()){
                n=n-arr.length();
            }
            sb.append(arr.charAt(n));
           
        }
        
        }
        
        
            
        return sb.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForthPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForthPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForthPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForthPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForthPage().setVisible(true);
            }
        });
    }
private void initialize() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pitagor_0.png")));
        
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables

}
