package newpackage;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
//ШИФЪР НА ВИЖЕНЕР
public class ThirdPage extends javax.swing.JFrame {

    /**
     * Creates new form ThirdPage
     */
    public ThirdPage() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(445, 608));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(222, 201, 162));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 560, 90, 25);

        jButton2.setBackground(new java.awt.Color(222, 201, 162));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Next>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 560, 90, 25);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("    Vigenere Cipher");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 60, 190, 30);

        jTextPane1.setBackground(new java.awt.Color(242, 228, 200));
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 150, 130, 60);

        jTextPane2.setBackground(new java.awt.Color(242, 228, 200));
        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 260, 130, 40);

        jTextPane3.setBackground(new java.awt.Color(242, 228, 200));
        jScrollPane3.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(60, 340, 130, 60);

        jTextField1.setBackground(new java.awt.Color(242, 228, 200));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 450, 130, 70);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel4.setText("Enter key");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 240, 70, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel5.setText("Enter code to decrypt");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 320, 120, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel3.setText("Enter text to encrypt");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 130, 120, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel6.setText("Result");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 430, 31, 14);

        jButton3.setBackground(new java.awt.Color(222, 201, 162));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 210, 90, 20);

        jButton4.setBackground(new java.awt.Color(222, 201, 162));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 400, 90, 20);

        jRadioButton1.setBackground(new java.awt.Color(222, 201, 162));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setLabel("BG");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(290, 150, 50, 23);

        jRadioButton2.setBackground(new java.awt.Color(222, 201, 162));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("EN");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(350, 150, 40, 23);

        jTextArea1.setBackground(new java.awt.Color(242, 228, 200));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(200, 180, 190, 340);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/vigener.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 20, 110, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/papirus_dyplom542.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 431, 618);

        setSize(new java.awt.Dimension(447, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Бутон back към предишната страница(Шифър на Цезар)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
SecondPage ff=new SecondPage();
           ff.setVisible(true);
           dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    //Бутон за криптиране 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try{
      String text=jTextPane1.getText().toUpperCase().replace(" ", "");
      StringBuilder sb=new StringBuilder();
      String key=jTextPane2.getText().toUpperCase();
      if(text.length()>=key.length()){
      int n=key.length();
      for(int i=0;key.length()!=text.length();i++){
          if(i==n){
              i=0;
          }
          key=key+key.charAt(i);
      }
        
      
      //System.out.println(key);
      String key1=key.charAt(0)+",";
      String text1=text.charAt(0)+",";
      String strEn="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,";
      String strBg="А,Б,В,Г,Д,Е,Ж,З,И,Й,К,Л,М,Н,О,П,Р,С,Т,У,Ф,Х,Ц,Ч,Ш,Щ,Ъ,Ь,Ю,Я,";
      //Проверка дали ключа се съсържа в масива от символи 
      if(strEn.contains(key1)){
          if(strEn.contains(text1)){
              jTextField1.setText(Encrypt(ArrVijenerEn(), key, text));
          }
      }
      else if(strBg.contains(key1)){
          if(strBg.contains(text1)){
              jTextField1.setText(Encrypt(ArrVijenerBg(), key, text));
          }
      }
      else {
          String message = "Please enter only cyrillic or english letters!";
          JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
      }
      }
      else{
          String message = "The text must be longer than the key!";
          JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
      }
     }catch(Exception e){
         //Съобщението
         
         String message = "Please enter values both for the key and the text!";
          JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
     }
//jTextField1.setText(Encrypt());
    }//GEN-LAST:event_jButton3ActionPerformed

    //Метод за криптиране
    public String Encrypt(String[] str,String key,String text){
      StringBuilder sb=new StringBuilder();
      StringBuilder sb1=new StringBuilder();
      StringBuilder sb2=new StringBuilder();
      //Записва се позицията на всеки от символите от първия ред на таблицата на Виженер
      //като след всяка позиция с слага запетая
      for(int j=0;j<text.length();j++){
      for(int i=0;i<str[0].length();i++){
          if(text.charAt(j)==str[0].charAt(i)){
             
                 sb.append(i);
                 sb.append(',');
                 System.out.print(text.charAt(j));
                 System.out.println(i);
            }
         }
                   
      }
      //Записва се позицията на всеки ред от таблицата на Виженер,
      //съдържащ като първи символ, символ от ключа  
      //като след всяка позиция с слага запетая
      for(int m=0;m<key.length();m++){
      for(int k=0;k<str.length;k++){
             if(str[k].charAt(0)==key.charAt(m)){
                     sb1.append(k);
                     sb1.append(',');
                     
                    
                 }
                 }
      }
      try{
          //Създават се два масива от позициите по ред и по колона
          //Масивите се създават, като се разделят стринговете където има запетая
          String s1[]=sb.toString().split(",");
          String s2[]=sb1.toString().split(",");
          //Записват се шифрованите символи 
      for(int p=0;p<s1.length;p++){
          int m=Integer.parseInt(s1[p]);
          int n=Integer.parseInt(s2[p]);
          
          sb2.append(str[n].charAt(m));
                         
          
      }
      }catch(Exception e1){
          //System.out.println("izbi gre6ka");
      } 
      
      return sb2.toString();
    }
    
    //Метод за Декриптиране
    public String Decrypt(String[] str,String key,String code){
      StringBuilder sb=new StringBuilder();
      StringBuilder sb1=new StringBuilder();
      StringBuilder sb2=new StringBuilder();
      //Записва се позицията на всеки ред от таблицата на Виженер,
      //съдържащ като първи символ, символ от ключа  
      //като след всяка позиция с слага запетая
          for(int j=0;j<key.length();j++){
              for(int k=0;k<str.length;k++){
                  if(key.charAt(j)==str[k].charAt(0)){
                      sb.append(k);
                      sb.append(",");
                      
                     
                  }
              }
          }
        int count=0;
        String posCode[]=sb.toString().split(",");
        //Претърсва се всеки един от редовете, намерини по горе, за съвпадение с криптограмата
        //При съвпадение се записва позицията
        for(int i=0;i<posCode.length;i++){
            int k=Integer.parseInt(posCode[i]);
                        
            for(int j=0;j<str[0].length();j++){
                if(str[k].charAt(j)==code.charAt(i)){
                    sb1.append(j);
                    sb1.append(",");
               }
            }
        }
        String posText[]= sb1.toString().split(",");
        //С намерените позиции на колоните се търсят символите в първия ред от таблицата на Виженер
        for(int i=0;i<posText.length;i++){
            sb2.append(str[0].charAt(Integer.parseInt(posText[i])));
            
        }
          
         
      return sb2.toString();
    }
    
    
    
    
    //Бутон за визуализиране на таблицата на Виженер с българската азбука
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       StringBuffer sb1=new StringBuffer();
       String st[]=ArrVijenerBg();
        for(int i=0;i<ArrVijenerBg().length;i++){
        sb1.append(st[i]);
        sb1.append(System.getProperty("line.separator"));
        }
        jTextArea1.setText(sb1.toString());
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    //Бутон за визуализиране на таблицата на Виженер с английската азбука
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        StringBuilder sb1=new StringBuilder();
       String st[]=ArrVijenerEn();
        for(int i=0;i<ArrVijenerEn().length;i++){
        sb1.append(st[i]);
        sb1.append(System.getProperty("line.separator"));;
        }
        jTextArea1.setText(sb1.toString());
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    //Бутона за декриптиране, аналогичрн на този за криптиране
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try{   
      String code=jTextPane3.getText().toUpperCase().replace(" ", "");
      StringBuilder sb=new StringBuilder();
      String key=jTextPane2.getText().toUpperCase();
       if(code.length()>=key.length()){
      int n=key.length();
      for(int i=0;key.length()!=code.length();i++){
          if(i==n){
              i=0;
          }
          key=key+key.charAt(i);
      }
      System.out.println(key);    
      
      //System.out.println(key);
      String key1=key.charAt(0)+",";
      String text1=code.charAt(0)+",";
      String strEn="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,";
      String strBg="А,Б,В,Г,Д,Е,Ж,З,И,Й,К,Л,М,Н,О,П,Р,С,Т,У,Ф,Х,Ц,Ч,Ш,Щ,Ъ,Ь,Ю,Я,";
      
      if(strEn.contains(key1)){
          if(strEn.contains(text1)){
              jTextField1.setText(Decrypt(ArrVijenerEn(), key, code));
          }
      }
      else if(strBg.contains(key1)){
          if(strBg.contains(text1)){
              jTextField1.setText(Decrypt(ArrVijenerBg(), key, code));
          }
      }
      else {
          String message = "Please enter only cyrillic or english letters!";
          JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
      }
      }
      else{
          String message = "The text must be longer than the key!";
          JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
      }
     }catch(Exception e){
         //Съобщението
         e.printStackTrace();
         String message = "Please enter values both for the key and the text!";
          JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.ERROR_MESSAGE);
     } 
    }//GEN-LAST:event_jButton4ActionPerformed
    //Бутон next препращата към следващата страница(Многоазбучно заместване)
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
ForthPage fp = new ForthPage();
fp.setVisible(true);
dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    //Метод за създаване на таблицата на Виженер с английската азбука
    public String[] ArrVijenerEn(){
        String strEn="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String strArr[]=new String[strEn.length()];
        StringBuilder sb;
        int n=strEn.length();
        
        for(int i=0;i<strEn.length();i++){
            sb=new StringBuilder();
            strArr[i]=strEn;
           // System.out.println(strArr[i]);
           for(int j=0;j<strEn.length()-1;j++){
               sb.append(strEn.charAt(j+1));
               
           }
           sb.append(strEn.charAt(0));
           strEn=sb.toString();
           
           
        }
        
        return strArr;
    }
    //Метод за създаване на таблицата на Виженер с българската азбука
    public String[] ArrVijenerBg(){
        String strBg="АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЬЮЯ";
        String strArr[]=new String[strBg.length()];
        StringBuilder sb;
        int n=strBg.length();
        
        for(int i=0;i<strBg.length();i++){
            sb=new StringBuilder();
            strArr[i]=strBg;
           
           for(int j=0;j<strBg.length()-1;j++){
               sb.append(strBg.charAt(j+1));
               
           }
           sb.append(strBg.charAt(0));
           strBg=sb.toString();
           
           
           
        }
        
        return strArr;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
private void initialize() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pitagor_0.png")));
        
    }
}
